/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SevenShiftsRouteImport } from './routes/seven-shifts'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as WeightPresetsRouteImport } from './routes/weight-presets'
import { Route as ApiTipClaimAccessRouteImport } from './routes/api/tip-claim.access'
import { Route as ApiTipClaimAssignmentsRouteImport } from './routes/api/tip-claim.assignments'
import { Route as ApiTipClaimAvailableRouteImport } from './routes/api/tip-claim.available'
import { Route as ApiTipClaimEmployeesRouteImport } from './routes/api/tip-claim.employees'
import { Route as ApiTipClaimShiftsRouteImport } from './routes/api/tip-claim.shifts'
import { Route as ApiTipClaimTipPoolShiftsRouteImport } from './routes/api/tip-claim.tip-pool-shifts'
import { Route as ApiTipClaimWeightPresetsRouteImport } from './routes/api/tip-claim.weight-presets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SevenShiftsRoute = SevenShiftsRouteImport.update({
  id: '/seven-shifts',
  path: '/seven-shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightPresetsRoute = WeightPresetsRouteImport.update({
  id: '/weight-presets',
  path: '/weight-presets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTipClaimAccessRoute = ApiTipClaimAccessRouteImport.update({
  id: '/api/tip-claim/access',
  path: '/api/tip-claim/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTipClaimAssignmentsRoute = ApiTipClaimAssignmentsRouteImport.update({
  id: '/api/tip-claim/assignments',
  path: '/api/tip-claim/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTipClaimAvailableRoute = ApiTipClaimAvailableRouteImport.update({
  id: '/api/tip-claim/available',
  path: '/api/tip-claim/available',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTipClaimEmployeesRoute = ApiTipClaimEmployeesRouteImport.update({
  id: '/api/tip-claim/employees',
  path: '/api/tip-claim/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTipClaimShiftsRoute = ApiTipClaimShiftsRouteImport.update({
  id: '/api/tip-claim/shifts',
  path: '/api/tip-claim/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTipClaimTipPoolShiftsRoute =
  ApiTipClaimTipPoolShiftsRouteImport.update({
    id: '/api/tip-claim/tip-pool-shifts',
    path: '/api/tip-claim/tip-pool-shifts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTipClaimWeightPresetsRoute =
  ApiTipClaimWeightPresetsRouteImport.update({
    id: '/api/tip-claim/weight-presets',
    path: '/api/tip-claim/weight-presets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/claims': typeof ClaimsRoute
  '/reports': typeof ReportsRoute
  '/seven-shifts': typeof SevenShiftsRoute
  '/tips': typeof TipsRoute
  '/weight-presets': typeof WeightPresetsRoute
  '/api/tip-claim/access': typeof ApiTipClaimAccessRoute
  '/api/tip-claim/assignments': typeof ApiTipClaimAssignmentsRoute
  '/api/tip-claim/available': typeof ApiTipClaimAvailableRoute
  '/api/tip-claim/employees': typeof ApiTipClaimEmployeesRoute
  '/api/tip-claim/shifts': typeof ApiTipClaimShiftsRoute
  '/api/tip-claim/tip-pool-shifts': typeof ApiTipClaimTipPoolShiftsRoute
  '/api/tip-claim/weight-presets': typeof ApiTipClaimWeightPresetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/claims': typeof ClaimsRoute
  '/reports': typeof ReportsRoute
  '/seven-shifts': typeof SevenShiftsRoute
  '/tips': typeof TipsRoute
  '/weight-presets': typeof WeightPresetsRoute
  '/api/tip-claim/access': typeof ApiTipClaimAccessRoute
  '/api/tip-claim/assignments': typeof ApiTipClaimAssignmentsRoute
  '/api/tip-claim/available': typeof ApiTipClaimAvailableRoute
  '/api/tip-claim/employees': typeof ApiTipClaimEmployeesRoute
  '/api/tip-claim/shifts': typeof ApiTipClaimShiftsRoute
  '/api/tip-claim/tip-pool-shifts': typeof ApiTipClaimTipPoolShiftsRoute
  '/api/tip-claim/weight-presets': typeof ApiTipClaimWeightPresetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/claims': typeof ClaimsRoute
  '/reports': typeof ReportsRoute
  '/seven-shifts': typeof SevenShiftsRoute
  '/tips': typeof TipsRoute
  '/weight-presets': typeof WeightPresetsRoute
  '/api/tip-claim/access': typeof ApiTipClaimAccessRoute
  '/api/tip-claim/assignments': typeof ApiTipClaimAssignmentsRoute
  '/api/tip-claim/available': typeof ApiTipClaimAvailableRoute
  '/api/tip-claim/employees': typeof ApiTipClaimEmployeesRoute
  '/api/tip-claim/shifts': typeof ApiTipClaimShiftsRoute
  '/api/tip-claim/tip-pool-shifts': typeof ApiTipClaimTipPoolShiftsRoute
  '/api/tip-claim/weight-presets': typeof ApiTipClaimWeightPresetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/claims'
    | '/reports'
    | '/seven-shifts'
    | '/tips'
    | '/weight-presets'
    | '/api/tip-claim/access'
    | '/api/tip-claim/assignments'
    | '/api/tip-claim/available'
    | '/api/tip-claim/employees'
    | '/api/tip-claim/shifts'
    | '/api/tip-claim/tip-pool-shifts'
    | '/api/tip-claim/weight-presets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/claims'
    | '/reports'
    | '/seven-shifts'
    | '/tips'
    | '/weight-presets'
    | '/api/tip-claim/access'
    | '/api/tip-claim/assignments'
    | '/api/tip-claim/available'
    | '/api/tip-claim/employees'
    | '/api/tip-claim/shifts'
    | '/api/tip-claim/tip-pool-shifts'
    | '/api/tip-claim/weight-presets'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/claims'
    | '/reports'
    | '/seven-shifts'
    | '/tips'
    | '/weight-presets'
    | '/api/tip-claim/access'
    | '/api/tip-claim/assignments'
    | '/api/tip-claim/available'
    | '/api/tip-claim/employees'
    | '/api/tip-claim/shifts'
    | '/api/tip-claim/tip-pool-shifts'
    | '/api/tip-claim/weight-presets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  ClaimsRoute: typeof ClaimsRoute
  ReportsRoute: typeof ReportsRoute
  SevenShiftsRoute: typeof SevenShiftsRoute
  TipsRoute: typeof TipsRoute
  WeightPresetsRoute: typeof WeightPresetsRoute
  ApiTipClaimAccessRoute: typeof ApiTipClaimAccessRoute
  ApiTipClaimAssignmentsRoute: typeof ApiTipClaimAssignmentsRoute
  ApiTipClaimAvailableRoute: typeof ApiTipClaimAvailableRoute
  ApiTipClaimEmployeesRoute: typeof ApiTipClaimEmployeesRoute
  ApiTipClaimShiftsRoute: typeof ApiTipClaimShiftsRoute
  ApiTipClaimTipPoolShiftsRoute: typeof ApiTipClaimTipPoolShiftsRoute
  ApiTipClaimWeightPresetsRoute: typeof ApiTipClaimWeightPresetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seven-shifts': {
      id: '/seven-shifts'
      path: '/seven-shifts'
      fullPath: '/seven-shifts'
      preLoaderRoute: typeof SevenShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight-presets': {
      id: '/weight-presets'
      path: '/weight-presets'
      fullPath: '/weight-presets'
      preLoaderRoute: typeof WeightPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tip-claim/access': {
      id: '/api/tip-claim/access'
      path: '/api/tip-claim/access'
      fullPath: '/api/tip-claim/access'
      preLoaderRoute: typeof ApiTipClaimAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tip-claim/assignments': {
      id: '/api/tip-claim/assignments'
      path: '/api/tip-claim/assignments'
      fullPath: '/api/tip-claim/assignments'
      preLoaderRoute: typeof ApiTipClaimAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tip-claim/available': {
      id: '/api/tip-claim/available'
      path: '/api/tip-claim/available'
      fullPath: '/api/tip-claim/available'
      preLoaderRoute: typeof ApiTipClaimAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tip-claim/employees': {
      id: '/api/tip-claim/employees'
      path: '/api/tip-claim/employees'
      fullPath: '/api/tip-claim/employees'
      preLoaderRoute: typeof ApiTipClaimEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tip-claim/shifts': {
      id: '/api/tip-claim/shifts'
      path: '/api/tip-claim/shifts'
      fullPath: '/api/tip-claim/shifts'
      preLoaderRoute: typeof ApiTipClaimShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tip-claim/tip-pool-shifts': {
      id: '/api/tip-claim/tip-pool-shifts'
      path: '/api/tip-claim/tip-pool-shifts'
      fullPath: '/api/tip-claim/tip-pool-shifts'
      preLoaderRoute: typeof ApiTipClaimTipPoolShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tip-claim/weight-presets': {
      id: '/api/tip-claim/weight-presets'
      path: '/api/tip-claim/weight-presets'
      fullPath: '/api/tip-claim/weight-presets'
      preLoaderRoute: typeof ApiTipClaimWeightPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  ClaimsRoute: ClaimsRoute,
  ReportsRoute: ReportsRoute,
  SevenShiftsRoute: SevenShiftsRoute,
  TipsRoute: TipsRoute,
  WeightPresetsRoute: WeightPresetsRoute,
  ApiTipClaimAccessRoute: ApiTipClaimAccessRoute,
  ApiTipClaimAssignmentsRoute: ApiTipClaimAssignmentsRoute,
  ApiTipClaimAvailableRoute: ApiTipClaimAvailableRoute,
  ApiTipClaimEmployeesRoute: ApiTipClaimEmployeesRoute,
  ApiTipClaimShiftsRoute: ApiTipClaimShiftsRoute,
  ApiTipClaimTipPoolShiftsRoute: ApiTipClaimTipPoolShiftsRoute,
  ApiTipClaimWeightPresetsRoute: ApiTipClaimWeightPresetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
