/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SevenShiftsRouteImport } from './routes/seven-shifts'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as WeightPresetsRouteImport } from './routes/weight-presets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SevenShiftsRoute = SevenShiftsRouteImport.update({
  id: '/seven-shifts',
  path: '/seven-shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightPresetsRoute = WeightPresetsRouteImport.update({
  id: '/weight-presets',
  path: '/weight-presets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/claims': typeof ClaimsRoute
  '/reports': typeof ReportsRoute
  '/seven-shifts': typeof SevenShiftsRoute
  '/tips': typeof TipsRoute
  '/weight-presets': typeof WeightPresetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/claims': typeof ClaimsRoute
  '/reports': typeof ReportsRoute
  '/seven-shifts': typeof SevenShiftsRoute
  '/tips': typeof TipsRoute
  '/weight-presets': typeof WeightPresetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/claims': typeof ClaimsRoute
  '/reports': typeof ReportsRoute
  '/seven-shifts': typeof SevenShiftsRoute
  '/tips': typeof TipsRoute
  '/weight-presets': typeof WeightPresetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/claims'
    | '/reports'
    | '/seven-shifts'
    | '/tips'
    | '/weight-presets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/claims'
    | '/reports'
    | '/seven-shifts'
    | '/tips'
    | '/weight-presets'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/claims'
    | '/reports'
    | '/seven-shifts'
    | '/tips'
    | '/weight-presets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  ClaimsRoute: typeof ClaimsRoute
  ReportsRoute: typeof ReportsRoute
  SevenShiftsRoute: typeof SevenShiftsRoute
  TipsRoute: typeof TipsRoute
  WeightPresetsRoute: typeof WeightPresetsRoute
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seven-shifts': {
      id: '/seven-shifts'
      path: '/seven-shifts'
      fullPath: '/seven-shifts'
      preLoaderRoute: typeof SevenShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight-presets': {
      id: '/weight-presets'
      path: '/weight-presets'
      fullPath: '/weight-presets'
      preLoaderRoute: typeof WeightPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  ClaimsRoute: ClaimsRoute,
  ReportsRoute: ReportsRoute,
  SevenShiftsRoute: SevenShiftsRoute,
  TipsRoute: TipsRoute,
  WeightPresetsRoute: WeightPresetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
